controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
post_delete:
    path:     /post/delete/{id}
    defaults: { _controller: AppBundle:PostDelete:delete }